export const LOAD_ALL_COMMAND_BY_OFFER = '[Grouping] : Load all command by offer';
export const LOAD_ALL_COMMAND_BY_OFFER_SUCCESS = '[Grouping] : Load all command by offer Success';
export const CHANGE_COMMAND_SELECTION = '[Grouping] : Change Command Selection';
export const CHANGE_AGGREGATED_ARTICLE_QUANTITY = '[Grouping] : Change Aggregated Article Quantity';
export const LOAD_AGGREGATED_ARTICLES = '[Grouping] : Load Aggregated Articles ';
export const LOAD_AGGREGATED_ARTICLES_SUCCESS = '[Grouping] : Load Aggregated Articles Success';
export const CLEAR_GROUPING = '[Grouping] : Clear ressources';
export const CREATE_COMMAND_AGGREGATE = '[Grouping] : submit command Aggregate';
export const CREATE_COMMAND_AGGREGATE_SUCCESS = '[Grouping] : submit command Aggregate Success';
